### PR TITLE
Introduce useful DB queries into version control

### PR DESCRIPTION
**Pull request by MSancaktutar**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CCD-1709

### Change description ###
Add Cleanup Queries to Source Repo - Def Store

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by marvincudjoe — APPROVED** [review]
lgtm

**Review by MSancaktutar — COMMENTED** [review]
Nice work. Thank you @dinesh1patel .

@kaanaktas , @rafalkalita   - Could you please give a further review to this?

**Comment by kaanaktas** [comment]
> Nice work. Thank you @dinesh1patel .
> 
> @kaanaktas , @rafalkalita - Could you please give a further review to this?

Some of these queries are enough complicated for reviewing for me. @dinesh1patel is that possible we can have a quick call tomorrow? We can make an interactive review if it is ok for you?

**Review by rafalkalita — APPROVED** [review]
Looks good

**Review by kaanaktas — APPROVED** [review]
lgtm

**Pull request merged**
